server:
  port: 7000

mybatis:
  type-aliases-package: group2.entity.pojo
  mapper-locations: classpath*:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

spring:
  application:
    name: user
  cloud:
    nacos:
      discovery:
        server-addr: 120.24.40.53:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.24.40.53:3306/db_user_0?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: user_admin
    password: hG7.O0oqws

ribbon:
  ReadTimeout: 5000
  ConnectTimeout: 5000

logging:
  level:
    group1:
      dao: debug