server:
  port: 9000

mybatis:
  type-aliases-package: group2.entity.pojo
  mapper-locations: classpath*:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

logging:
  level:
    group1:
      dao: debug