server:
  port: 7000

mybatis:
  type-aliases-package: group2.entity.pojo
  mapper-locations: classpath*:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://120.24.40.53:3306/db_user_0?characterEncoding=utf-8
    username: user_admin
    password: kuKQ.rjh23u


logging:
  level:
    cn:
      edu:
        hqu:
          cst:
            dao: debug